### ISSUE TITLE
add info in the documentation about the dependencies needed

### ISSUE THREAD

**Issue by daniel-bolanos** [watson-developer-cloud/speech-to-text-websockets-ruby#3]
Add info in the documentation about the dependencies needed.

**Comment by kasaby** [comment]
https://github.com/watson-developer-cloud/speech-to-text-websockets-ruby/pull/5
Please check if this solves the issue

**Comment by germanattanasio** [comment]
@kasaby you need to use a GemFile to specify dependencies.

See an example here: https://github.com/watson-developer-cloud/relationship-extraction-ruby

**Comment by kasaby** [comment]
@germanattanasio please check this https://github.com/watson-developer-cloud/speech-to-text-websockets-ruby/pull/6

**Comment by germanattanasio** [comment]
thanks
